global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'execution_client_geth'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /debug/metrics/prometheus
    scheme: http
    static_configs:
      - targets: ['execution:6060']

  - job_name: 'consensus_client_lighthouse'
    static_configs:
      - targets: ['consensus:5054']

  - job_name: 'validator_client_lighthouse'
    static_configs:
      - targets: ['validator:5064']      
      
  - job_name: 'web3signer'
    static_configs:
      - targets: ['web3signer:9001']